### ISSUE TITLE
Does not run in background

### ISSUE THREAD

**Issue by byronigoe** [blockbasti/just_another_workout_timer#18]
Great app. Very simple and clean. However, it needs to be able to continue to countdown and announce when the screen is off/locked.

To reproduce the problem, start a workout then press the power button to lock your phone. The countdown will pause.

I want to use this for longer run/walk interval training with my phone in my pocket, so the option for "Keep screen awake" is not suitable.

Thanks for making this!

**Comment by blockbasti** [comment]
Hey @byronigoe, thanks for your feedback.

I can't reproduce your problem. I've tried it on different devices and when locking the screen, either with the lock button or because of the screen timeout, the sounds continue normally for me.

Which device and Android version are you using?

**Comment by byronigoe** [comment]
Samsung Galaxy S9 with Android 10. I'm running v1.1.1 of JAWT. I have added JAWT to the "Apps that won't be put to sleep" list, but nevertheless the full workout will not run.

For testing I created a simple "Plank" routine with 1 Set with 1 Rep of 4 Exercises (Front, Left, Back, Right) each of which is 30 seconds. I pressed play and hear the prompt "First Front". Then I press the power button. A few seconds later I hear "3...2...1...Front". I waited a couple minutes and heard nothing further. Then I unlock my phone and there are 20 seconds left in "Front" and it starts counting down again. So, the timer stopped counting down about 15 seconds after the phone was locked.

Let me know if I can provide a logcat, or run any other tests to help you debug.

**Comment by blockbasti** [comment]
I've tried it on a Samsung phone running android 10 as well using JAWT 1.3.0 and i had no problem when locking the screen. Announcements kept playing normally. Maybe try the newest version 1.3.0 of the app from GitHub and see if that helps.

F-Droid is always a bit slow with pushing updates. If you don't want to reinstall the app, you can download the zip from the CI run (https://github.com/blockbasti/just_another_workout_timer/actions/runs/551246653), and install the APK from there, because it can be installed alongside the F-Droid version (or GitHub release for that matter).

**Comment by byronigoe** [comment]
v1.3.0 seems to have resolved it. Thanks!

**Comment by defanor** [comment]
I ran into the same behaviour with Just Another Workout Timer version 1.11.2, Android 13 on Google Pixel 6a. Then it resumes upon turning the screen on.

Setting "App battery usage" to "unrestricted" for JAWT did not help, but as a workaround, enabling "play tick every second" in JAWT apparently prevents the system from putting it to sleep.
